name: purfect_care
description: A simple pet care manager app.
version: 0.1.0
publish_to: "none"

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.14
  image_picker: ^1.2.0
  flutter_local_notifications: ^19.5.0
  timezone: ^0.10.1
  intl: ^0.20.2
  collection: ^1.17.1
  http: ^1.2.0
  shared_preferences: ^2.2.2
  fl_chart: ^0.69.0
  cached_network_image: ^3.3.1
  photo_view: ^0.14.0
  table_calendar: ^3.1.2
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  google_sign_in: ^6.2.1
  cloud_firestore: ^6.1.1
  firebase_storage: ^13.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  config:
    enable-lldb-debugging: false
  assets:
    - assets/images/
    - assets/images/pets/
    - assets/icons/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/purfect_care_icon.png"
  android_adaptive_icon:
    foreground_image: "assets/icons/purfect_care_icon.png"
    background_image: "assets/icons/purfect_care_icon.png"
    background_color: "#00000000"
  remove_alpha_ios: true

